### ISSUE TITLE
Improving the filter Feature in the Menu

### ISSUE THREAD

**Issue by tanish0912** [sajalbatra/foodzy#18]
In the Menu tab currently
we can sort only one type of dish or all dishes 
but if we want to sort multiple dishes that is not currently done.
Also which filter is selected that is not properly displayed.
https://foodzyy.vercel.app/menu
<img width="1313" alt="Screenshot 2024-10-09 at 1 10 37 AM" src="https://github.com/user-attachments/assets/ec3fddfa-55bf-48a1-81a5-e74087c40dab">
Please assign me this issue i am ready to work on this.
Thanks

**Comment by tanish0912** [comment]
Please assign me this.

**Comment by tanish0912** [comment]
Any Update?

**Comment by sajalbatra** [comment]
Also add search bar to search a dish

**Comment by tanish0912** [comment]
I will try my best to add a search bar.

**Comment by tanish0912** [comment]
I have solved the issue, please check. 
https://github.com/sajalbatra/foodzy/pull/57
Above is the pull request which i have raised.
Thanks! Happy to help.
