### ISSUE TITLE
Feature: Adding a 404 error page

### ISSUE THREAD

**Issue by ShinichiShi** [sajalbatra/foodzy#23]
1. I can add an error 404 page...for improper routing to other pages
2. Also, adding a link to redirect user to homepage

Kindly assign this issue to me, so that i can raise my PR soon !

**Comment by gautamkhokhar0001** [comment]
hii @sajalbatra 
I can add the 404 error page, pls assign me this issue.

**Comment by sajalbatra** [comment]
Do it
