### ISSUE TITLE
Adding restaurant auth

### ISSUE THREAD

**Issue by surajgsn07** [sajalbatra/foodzy#26]
This is the schema for the restaurant 
i will be storing images as base 64 for now (as there is no cloud storage for now) 
lat , long - for integrating map in future. 

const restaurantSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  address: {
    type: String,
    required: true
  },
  coordinates: {
    latitude: {
      type: Number,
      required: true
    },
    longitude: {
      type: Number,
      required: true
    }
  },
  description: {
    type: String,
  },
  image: [{
    type: String, 
    required: false
  }],
password:{type:String},
username : { type : string },
email : {type : string}
});

Adding table and booking schema for further use . 
const tableSchema = new mongoose.Schema({
  tableNumber: {
    type: Number,
    required: true,
  },
  capacity: {
    type: Number,
    required: true,
  },
  isAvailable: {
    type: Boolean,
    default: true
  },
  restaurant: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Restaurant',
    required: true
  }
});

const bookingSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',            // Assuming a User schema exists
    required: true
  },
  restaurant: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Restaurant',
    required: true
  },
  table: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Table',
    required: true
  },
  bookingDate: {
    type: Date,
    required: true
  },
  timeSlot: {
    type: String,
    required: true          // For example: '18:00 - 20:00'
  },
  status: {
    type: String,
    enum: ['confirmed', 'cancelled', 'completed'],
    default: 'confirmed'
  },
  createdAt: {
    type: Date,
    default: Date.now
  }
});

**Comment by surajgsn07** [comment]
i have added the pr...can you please check my pr..

**Comment by sajalbatra** [comment]
Merged
