### ISSUE TITLE
The User page is buggy as the sign up form appears above the header and navbar.

### ISSUE THREAD

**Issue by Pujan-khunt** [sajalbatra/foodzy#27]
It can be clearly seen that the sign up form appears above the navbar and the header.

![image](https://github.com/user-attachments/assets/eea44d71-f2ea-4b3f-84a3-cfa3c60176d2)

Fix: Modify the CSS for Sign Up form so it appears below the header and navbar

Please assign this issue to me so I can quickly send the PR. Also can you please add the Hacktoberfest label?

**Comment by sajalbatra** [comment]
it is fixed
