### ISSUE TITLE
Footer Instagram Link Should be an Anchor Tab

### ISSUE THREAD

**Issue by mohit-1710** [sajalbatra/foodzy#30]
# Issue: Footer Instagram Link Should be an Anchor Tab

## Description
The footer section currently includes text that says "Follow us on Instagram," but it is not set up as a clickable link. This makes it difficult for users to navigate to our Instagram profile directly.

## Suggested Solution
I suggest updating the text to an anchor tag so that when users click on "Follow us on Instagram," they will be redirected to your Instagram profile.

**Comment by mohit-1710** [comment]
@sajalbatra please assign this issue to me .

**Comment by sajalbatra** [comment]
We donot have any socials now. 
So i am closing the issue as of now
