### ISSUE TITLE
Feature Request: Add Scroll Up Button

### ISSUE THREAD

**Issue by mohit-1710** [sajalbatra/foodzy#31]
# Feature Request: Add Scroll Up Button

## Description
I would like to propose the addition of a scroll-up button at the bottom of the website. This feature will allow users to quickly return to the top of the page without having to scroll manually.

## Suggested Implementation
The scroll-up button can be a floating button that appears when users scroll down the page. When clicked, it will smoothly scroll the user back to the top.

### Example Code
Here’s a sample implementation using HTML, CSS, and JavaScript:

```html
<!-- HTML -->
<button id="scrollUpBtn" style="display: none;">↑</button>

**Comment by mohit-1710** [comment]
@sajalbatra please assign this issue to me .

**Comment by princetoday** [comment]
can you assign me i love to work on html and css and javascript.

**Comment by sajalbatra** [comment]
@mohit-1710 Assigned
