### ISSUE TITLE
The links present in the footer  is not Working

### ISSUE THREAD

**Issue by Jils31** [sajalbatra/foodzy#36]
The links present in the footer section of the website are not working .

https://github.com/user-attachments/assets/9b02a9c4-a853-4c98-b297-6d32e70ac2c2

Assign this issue to me, I can solve it!

**Comment by sajalbatra** [comment]
Also add 404 page.
If no page is found redirect to it.

**Comment by Jils31** [comment]
The 404 page is not added in the pull request , so i'll  update it in the next commit
